{
 "title": "BlueSense",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(job_last_success_unixtime, exported_job)"
   },
   {
    "name": "interval",
    "query": "5s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "temp{job=\"pushgateway\", exported_job=\"$job\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hum{job=\"pushgateway\", exported_job=\"$job\"}",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "Air Pollutant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ug/m^3" }
   ],
   "targets": [
    {
     "expr": "pm10{job=\"pushgateway\", exported_job=\"$job\"}",
     "legendFormat": "PM10"
    },
    {
     "expr": "pm25{job=\"pushgateway\", exported_job=\"$job\"}",
     "legendFormat": "PM2.5"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pa{job=\"pushgateway\", exported_job=\"$job\"}",
     "legendFormat": "Pressure"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Data Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(collected_points_total{job=\"pushgateway\", exported_job=\"$job\"}[1m])",
     "legendFormat": "data update per second"
    }
   ]
  },
  {
   "title": "Serial Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(channel_serial_packet_event_total{job=\"pushgateway\", exported_job=\"$job\"}[1m])",
     "legendFormat": "serial packet per second"
    },
    {
     "expr": "rate(channel_serial_error_event_total{job=\"pushgateway\", exported_job=\"$job\"}[1m])",
     "legendFormat": "serial error per second"
    }
   ]
  },
  {
   "title": "Protobuf Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(channel_protobuf_packet_event_total{job=\"pushgateway\", exported_job=\"$job\"}[1m])",
     "legendFormat": "protobuf packet per second"
    },
    {
     "expr": "rate(channel_protobuf_error_event_total{job=\"pushgateway\", exported_job=\"$job\"}[1m])",
     "legendFormat": "protobuf error per second"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 25 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "job_last_success_unixtime{exported_job=\"$job\"} * 1000"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "ug/m^3" }
   ],
   "targets": [
    {
     "expr": "timestamp(job_last_success_unixtime{job=\"pushgateway\", exported_job=\"$job\"}) - job_last_success_unixtime{job=\"pushgateway\", exported_job=\"$job\"} < bool 5",
     "legendFormat": "Availability"
    }
   ]
  },
  {
   "title": "Last Startup Time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "job_start_unixtime{exported_job=\"$job\"} * 1000"
    }
   ]
  }
 ]
}